import scrapy

class JobItem(scrapy.Item):
    slug = scrapy.Field()
    language = scrapy.Field()
    req_id = scrapy.Field()
    title = scrapy.Field()
    description = scrapy.Field()
    street_address = scrapy.Field()
    city = scrapy.Field()
    state = scrapy.Field()
    country_code = scrapy.Field()
    postal_code = scrapy.Field()
    latitude = scrapy.Field()
    longitude = scrapy.Field()
    categories = scrapy.Field()
    tags = scrapy.Field()
    brand = scrapy.Field()
    employment_type = scrapy.Field()
    hiring_organization = scrapy.Field()
    apply_url = scrapy.Field()
    create_date = scrapy.Field(serializer=str)
    meta_data = scrapy.Field()
    googlejobs = scrapy.Field()